[package]

name = "tenderdash-proto"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/dashpay/rs-tenderdash-abci/tree/main/proto"
documentation = "https://dashpay.github.io/rs-tenderdash-abci/tenderdash_proto/"
readme = "README.md"
categories = [
    "cryptography",
    "cryptography::cryptocurrencies",
    "database",
    "dash",
    "tenderdash",
]
keywords = ["blockchain", "tenderdash", "proto"]

description = """
    tenderdash-proto is a the Rust implementation of the Tenderdash proto structs.
    """

rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
# Features configuration.
#
# Note that, due to the way build.rs scripts work, change of features does not trigger
# regeneration of protobuf files. This means you need to be extra careful when changing
# features, as you might end up with outdated and/or conflicting generated files.
#
# Sometimes cleaning the build cache with `cargo clean` might be necessary to solve
# issues related to outdated generated files.
default = ["server"]

# Enable standard library support; DEPRECATED - use `client` and/or `server` instead
std = ["client"]
# Enable gRPC support using tonic; internal, consider using `server` or `client` instead
grpc = ["client", "dep:tonic", "tonic/codegen", "tonic/prost"]
# Build gRPC server using tonic. Includes `client` feature.
server = ["client", "tonic/transport"]
# Build minimal gRPC client using tonic, without transport
client = ["tenderdash-proto-compiler/grpc", "prost/std", "grpc"]

serde = ["dep:serde", "bytes/serde"]

[dependencies]
bytes = { version = "1.7", default-features = false }
prost = { version = "0.13", default-features = false, features = [
    "prost-derive",
] }
tonic = { version = "0.12.3", optional = true, default-features = false }
serde = { version = "1.0.208", default-features = false, features = [
    "derive",
], optional = true }
subtle-encoding = { version = "0.5.1", default-features = false, features = [
    "hex",
    "base64",
    "alloc",
] }
num-traits = { version = "0.2.19", default-features = false }
num-derive = { version = "0.4.2", default-features = false }
time = { version = "0.3.36", default-features = false, features = [
    "macros",
    "parsing",
] }
flex-error = { version = "0.4.4", default-features = false }
chrono = { version = "0.4.38", default-features = false }
derive_more = { version = "1.0", features = ["from", "from_str"] }


[dev-dependencies]
serde_json = { version = "1.0.125", default-features = false, features = [
    "alloc",
] }

[build-dependencies]
tenderdash-proto-compiler = { path = "../proto-compiler" }
