---
name: Audit-Check
on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo bin
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-audit
      - uses: actions-rs/audit-check@v1
        name: Audit check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
